server:
  port: 8082

spring:
  application:
    name: proyecto-service
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mensaje:
  servicio: "Proyecto Service activo desde Config Server"

resilience4j:
  circuitbreaker:
    instances:
      usuarioService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      usuarioService:
        max-attempts: 3
        wait-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics