server:
  port: 8083

spring:
  application:
    name: tarea-service
  datasource:
    url: jdbc:mysql://localhost:3306/tarea_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mensaje:
  servicio: "Tarea Service activo desde Config Server"

resilience4j:
  circuitbreaker:
    instances:
      proyectoService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      proyectoService:
        max-attempts: 3
        wait-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics